import discord
from discord import Interaction, ButtonStyle, File
from typing import Union, Callable, List, Tuple, AsyncContextManager, Optional
import aiohttp
import io
from io import BytesIO
import datetime
import uuid
from PIL import Image
from urllib.parse import quote, urlencode
import logging
from redbot.core import commands

log = logging.getLogger("red.glas-cogs.aigen")

async def create_typing_and_send(
    ctx: Union[Interaction, commands.Context],
) -> Tuple[AsyncContextManager, Callable]:
    """Creates typing context manager and send function based on context type"""
    if isinstance(ctx, commands.Context):
        typing_cm = ctx.typing()

        async def send_func(*args, **kwargs):
            try:
                await ctx.send(*args, **kwargs)
            except Exception:
                try:
                    await ctx.send("Something went wrong, please try again.")
                except Exception:
                    pass

        return typing_cm, send_func

    elif isinstance(ctx, Interaction):
        typing_cm = ctx.channel.typing()

        async def send_func(*args, **kwargs):
            try:
                if not ctx.response.is_done():
                    await ctx.response.send_message(*args, **kwargs)
                else:
                    await ctx.followup.send(*args, **kwargs)
            except Exception:
                try:
                    if not ctx.response.is_done():
                        await ctx.response.send_message(
                            "Something went wrong, please try again.",
                            ephemeral=True,
                        )
                    else:
                        await ctx.followup.send(
                            "Something went wrong, please try again.",
                            ephemeral=True,
                        )
                except Exception:
                    pass

        return typing_cm, send_func

    raise TypeError("ctx must be Context or Interaction")


async def create_image_embed(
    title: str,
    prompt: str,
    author: Union[discord.Member, discord.User],
    params: dict,
    images: List[str] = None,
) -> discord.Embed:
    """Creates a standardized embed for image generation responses"""
    embed = discord.Embed(title=title)
    embed.set_image(url="attachment://generated.png")

    if len(prompt) > 1024:
        prompt = prompt[:1024]
    embed.add_field(name="Prompt", value=f"```\n{prompt}\n```", inline=False)

    if images:
        embed.add_field(
            name="Reference Images",
            value="\n".join([f"[Image {i+1}]({img})" for i, img in enumerate(images)]),
            inline=False,
        )

    for key, value in params.items():
        if key.lower() not in ["private", "nologo", "referrer", "enhance", "image"]:
            safe_field(embed, key, value, inline=True)

    embed.set_footer(
        text=f"Generated by {author} • {datetime.datetime.utcnow().strftime('%m/%d/%Y %I:%M %p')} • Powered by Pollinations.ai"
    )
    return embed


async def create_button_view(
    regenerate_callback: Callable, edit_callback: Callable, delete_callback: Callable
) -> discord.ui.View:
    """Creates a standardized button view for image generation responses"""
    view = discord.ui.View()

    regenerate_button = discord.ui.Button(label="Regenerate", style=ButtonStyle.green)
    edit_button = discord.ui.Button(label="Edit", style=ButtonStyle.blurple)
    delete_button = discord.ui.Button(label="Delete", style=ButtonStyle.red)

    regenerate_button.callback = regenerate_callback
    edit_button.callback = edit_callback
    delete_button.callback = delete_callback

    view.add_item(regenerate_button)
    view.add_item(edit_button)
    view.add_item(delete_button)

    return view

def safe_field(embed: discord.Embed, name: str, value: any, inline: bool = False):
    """Safely adds a field to an embed, trimming value if it exceeds Discord's limit"""
    value = str(value)
    wrapped = f"```\n{value}\n```"
    if len(wrapped) > 1024:
        trimmed = value[:1000] + "..."
        wrapped = f"```\n{trimmed}\n```"
    embed.add_field(name=name, value=wrapped, inline=inline)

async def process_image(url: str, logger: Optional[logging.Logger] = None) -> Tuple[Optional[io.BytesIO], str]:
    """Processes an image from a URL, resizing if it's too small"""
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(url) as r:
                data = await r.read()
        img = Image.open(io.BytesIO(data))
        min_size = 300
        if img.width < min_size or img.height < min_size:
            ratio = max(min_size / img.width, min_size / img.height)
            img = img.resize((int(img.width * ratio), int(img.height * ratio)), Image.LANCZOS)
            buf = io.BytesIO()
            img.save(buf, format="PNG")
            buf.seek(0)
            return buf, f"image_{uuid.uuid4()}.png"
        return None, url
    except Exception as e:
        if logger:
            logger.error(f"Image processing failed for {url}: {e}")
        return None, url
