# Credits to /hlgg/ for most of the images.
# All images credits goes to the rightful owner of each image.

mogo = {
    "image": [
"https://i.imgur.com/hIgvkSx.png",
"https://i.imgur.com/SePPaGx.png",
"https://i.imgur.com/3FzxLXv.jpeg",
"https://i.imgur.com/d0xJIP4.jpeg",
"https://i.imgur.com/rImWgve.jpeg",
"https://i.imgur.com/Sqqgaak.jpeg",
"https://i.imgur.com/tP2ZEyx.png",
"https://i.imgur.com/u4qFSM2.png",
"https://i.imgur.com/5c8pllW.jpeg",
"https://i.imgur.com/3L4JZQ4.png",
"https://i.imgur.com/VwgcGJH.jpeg",
"https://i.imgur.com/uLgRQ8k.jpeg",
"https://i.imgur.com/ZtG2i1q.jpeg",
"https://i.imgur.com/WtQT9l0.jpeg",
"https://i.imgur.com/aUPKTcz.jpeg",
"https://i.imgur.com/EfRXQUv.jpeg",
"https://i.imgur.com/G2N0D5D.jpeg",
"https://i.imgur.com/MK6g2cC.jpeg",
"https://i.imgur.com/xgIToki.jpeg",
"https://i.imgur.com/F6HwGls.jpeg",
"https://i.imgur.com/VnscDMA.jpeg",
"https://i.imgur.com/1eDIdIX.jpeg",
"https://i.imgur.com/OmZZqRK.jpeg",
"https://i.imgur.com/QwZ2hes.jpeg",
"https://i.imgur.com/4UG43YM.jpeg",
"https://i.imgur.com/gyVh2cx.jpeg",
"https://i.imgur.com/DbC6w0F.png",
"https://i.imgur.com/xFxdOrF.jpeg",
"https://i.imgur.com/cSHwWwr.jpeg",
"https://i.imgur.com/GnJSPYW.png",
"https://i.imgur.com/AxZA0UN.jpeg",
"https://i.imgur.com/2aLWKRy.png",
"https://i.imgur.com/NlW4xcz.jpeg",
"https://i.imgur.com/I8ObzyB.png",
"https://i.imgur.com/UmDEoZg.png",
"https://i.imgur.com/HaErcwU.jpeg",
"https://i.imgur.com/J0EeDQ2.png",
"https://i.imgur.com/j2l0be9.png",
"https://i.imgur.com/rEjBlF0.png",
"https://i.imgur.com/7IDDG3C.png",
"https://i.imgur.com/heAXlZt.gif",
"https://i.imgur.com/4YiN1Dl.jpeg",
"https://i.imgur.com/Ha9u3fp.png",
"https://i.imgur.com/0GY5KhT.png",
"https://i.imgur.com/9PQVYvV.jpeg",
"https://i.imgur.com/tq1SwQr.jpeg",
"https://i.imgur.com/MW09tvq.jpeg",
"https://i.imgur.com/KMAecqM.jpeg",
"https://i.imgur.com/L0bvsAb.jpeg",
"https://i.imgur.com/SaKD7HM.png",
"https://i.imgur.com/gdXLyTb.png",
]}
