# Credits to /hlgg/ for most of the images.
# All images credits goes to the rightful owner of each image.

ogey = {
    "image": [
        "https://i.imgur.com/jFVzGSb.jpeg",
        "https://i.imgur.com/vd9g4qO.png",
        "https://i.imgur.com/oySXqwd.png",
        "https://i.imgur.com/JvqEzgS.jpeg",
        "https://i.imgur.com/WpILHps.png",
        "https://i.imgur.com/MsccK64.png",
        "https://i.imgur.com/67riGez.png",
        "https://i.imgur.com/gWJWc2R.jpeg",
        "https://i.imgur.com/HkPEMeP.jpeg",
        "https://i.imgur.com/qudIcMu.png",
        "https://i.imgur.com/fyHfrpe.jpeg",
        "https://files.catbox.moe/qoe57j.png",
        "https://files.catbox.moe/gxj7u2.png",
        "https://files.catbox.moe/4f9d1r.png",
        "https://files.catbox.moe/gxj7u2.png",
    ],
    "gif": [
        "https://files.catbox.moe/m73l5q.gif",
        "https://files.catbox.moe/b40gou.gif",
        "https://files.catbox.moe/vd25ad.gif",
        "https://files.catbox.moe/j95uui.gif",
        "https://files.catbox.moe/jpl3j4.gif",
        "https://files.catbox.moe/1lbqxs.gif",
        "https://files.catbox.moe/f4ny5p.gif",
        "https://files.catbox.moe/mmbed9.gif",
        "https://files.catbox.moe/q58ast.gif",
        "https://files.catbox.moe/m73l5q.gif",
        "https://files.catbox.moe/8gac5d.gif",
        "https://files.catbox.moe/blz34k.gif",
        "https://files.catbox.moe/bacgjo.gif",
        "https://files.catbox.moe/m88zv8.png",
        "https://files.catbox.moe/slpdv9.gif",
        "https://files.catbox.moe/u66z2s.gif",
        "https://files.catbox.moe/fm9w3e.gif",
        "https://files.catbox.moe/mkf8ox.gif",
        "https://files.catbox.moe/qknrnh.gif",
        "https://files.catbox.moe/qyvnm9.gif",
        "https://files.catbox.moe/perc3r.gif",
        "https://files.catbox.moe/4mrx1f.gif",
        "https://files.catbox.moe/ifj52h.gif",
        "https://files.catbox.moe/hvueda.gif",
        "https://i.imgur.com/u2Q5zg5.gif",
        "https://i.imgur.com/jYX41KZ.gif",
        "https://i.imgur.com/YOATvsC.gif",
        "https://i.imgur.com/EvHkvmf.gif",
        "https://i.imgur.com/19tWhxs.gif",
        "https://i.imgur.com/VRjdpjb.gif",
        "https://i.imgur.com/FtyMZuL.gif",
        "https://i.imgur.com/enuslLI.gif",
        "https://i.imgur.com/bUgJCvu.gif",
        "https://i.imgur.com/COOAuMw.gif",
        "https://i.imgur.com/9keeYIS.gif",
        "https://i.imgur.com/vTO4f6H.gif",
        "https://i.imgur.com/oSb2ZEc.gif",
        "https://i.imgur.com/zUGAdna.gif",
        "https://i.imgur.com/hOkuR9X.gif",
        "https://i.imgur.com/Wf2E5oK.gif",
        "https://i.imgur.com/FrlX0OL.gif",
        "https://i.imgur.com/WD4vUFa.gif",
        "https://i.imgur.com/UtOewFV.gif",
        "https://i.imgur.com/fhGSH23.gif",
        "https://i.imgur.com/klewZkg.gif",
        "https://i.imgur.com/OaEsaRb.gif",
        "https://i.imgur.com/pW9G5xW.gif",
        "https://i.imgur.com/Ekkx9Dd.gif",
        "https://i.imgur.com/yfXXDPs.gif",
        "https://i.imgur.com/xJbpXM6.gif",
        "https://i.imgur.com/QXTWENl.gif",
        "https://i.imgur.com/NONKNrV.gif",
        "https://i.imgur.com/dizcjdL.gif",
        "https://i.imgur.com/gJL6FBu.gif",
        "https://i.imgur.com/AVTiBDj.gif",
        "https://i.imgur.com/DhFbdjh.gif",
        "https://i.imgur.com/xWP5X3d.gif",
        "https://i.imgur.com/bYZKLEM.gif",
        "https://i.imgur.com/6OMNiKf.gif",
        "https://i.imgur.com/iPgUfjH.gif",
        "https://i.imgur.com/XsFr1NM.gif",
        "https://i.imgur.com/L8TYW0E.gif",
        "https://i.imgur.com/zcyKgkR.gif",
        "https://i.imgur.com/Mt6gM0l.gif",
        "https://i.imgur.com/WJKHAIY.gif",
        "https://i.imgur.com/Bc7NIAW.gif",
    ],
    # "videos" : [
    #     "https://telegra.ph/file/f2235dde2263d69cb5e22.mp4",
    #     "https://telegra.ph/file/d414452895ef211ecb8d7.mp4"
    # ]
}
