# Credits to /watamelon/ for most of the images.
# All images credits goes to the rightful owner of each image.

watamelon = {
    "image": [
        "https://files.catbox.moe/mzwreb.jpg",
        "https://files.catbox.moe/5s8krx.png",
        "https://files.catbox.moe/cxcqmk.jpg",
        "https://files.catbox.moe/qkckyj.png",
        "https://files.catbox.moe/honwk5.png",
        "https://files.catbox.moe/8v4hdw.png",
        "https://files.catbox.moe/i8ndo5.jpg",
        "https://files.catbox.moe/y4m6gs.jpg",
        "https://files.catbox.moe/hv6g7q.png",
        "https://files.catbox.moe/ur5ufd.png",
        "https://files.catbox.moe/fccy3d.png",
        "https://files.catbox.moe/g5t5ky.png",
        "https://files.catbox.moe/08zwv0.png",
        "https://files.catbox.moe/4gism9.png",
        "https://files.catbox.moe/jsnh75.png",
        "https://files.catbox.moe/ppapra.png",
        "https://files.catbox.moe/v6q5vw.png",
        "https://files.catbox.moe/rwpqfz.png",
        "https://files.catbox.moe/8di1iv.jpg",
        "https://files.catbox.moe/42wylc.png",
        "https://files.catbox.moe/5q2374.png",
        "https://files.catbox.moe/0a27mg.jpg",
        "https://files.catbox.moe/i86e0h.jpg",
        "https://files.catbox.moe/gpt8iq.gif",
        "https://files.catbox.moe/gyvevd.jpg",
        "https://files.catbox.moe/z49mcm.jpg",
        "https://files.catbox.moe/0orve9.jpg",
        "https://files.catbox.moe/6zb0tv.png",
        "https://files.catbox.moe/5bxrc9.png",
        "https://files.catbox.moe/xidd6k.jpg",
        "https://files.catbox.moe/feumn6.png",
        "https://files.catbox.moe/sq1n6l.png",
        "https://files.catbox.moe/613xsu.jpg",
        "https://files.catbox.moe/0dl5lc.jpg",
        "https://files.catbox.moe/5mh5z6.jpg",
        "https://files.catbox.moe/5h7me5.jpg",
        "https://files.catbox.moe/y4f5ig.jpg",
        "https://files.catbox.moe/wmp7cl.jpg",
        "https://files.catbox.moe/yih8bz.jpg",
        "https://files.catbox.moe/ece4go.jpg",
        "https://files.catbox.moe/r8rxbe.jpg",
        "https://files.catbox.moe/rgr45i.jpg",
        "https://files.catbox.moe/e8sap7.jpg",
        "https://files.catbox.moe/y0x9zr.jpg",
        "https://files.catbox.moe/fdjkse.jpg",
        "https://files.catbox.moe/xr6ngb.jpg",
        "https://files.catbox.moe/613xsu.jpg",
        "https://files.catbox.moe/feumn6.png",
        "https://files.catbox.moe/6qc4x2.jpg",
        "https://files.catbox.moe/mjuhqv.png",
        "https://files.catbox.moe/33bq9r.png",
        "https://files.catbox.moe/yk15os.jpg",
        "https://files.catbox.moe/oixjfb.jpg",
        "https://files.catbox.moe/22gkn9.png",
        "https://files.catbox.moe/cx6xcl.png",
        "https://files.catbox.moe/34m8cq.jpg",
        "https://files.catbox.moe/380rwa.png",
        "https://files.catbox.moe/9ractq.jpg",
        "https://files.catbox.moe/2mgpj5.jpg",
        "https://files.catbox.moe/ua42df.jpg",
        "https://files.catbox.moe/33bq9r.png",
        "https://files.catbox.moe/ttfhoj.png",
        "https://files.catbox.moe/yk15os.jpg",
        "https://files.catbox.moe/8hduq2.png",
        "https://files.catbox.moe/5qpqzb.jpg",
        "https://files.catbox.moe/u2ieoe.jpg",
        "https://files.catbox.moe/iv1rik.jpg",
    ],
    "gif": [
        "https://files.catbox.moe/2tpt83.gif",
        "https://files.catbox.moe/92pld0.gif",
        "https://files.catbox.moe/ucy6ic.gif",
        "https://files.catbox.moe/t1n0aj.gif",
        "https://files.catbox.moe/ukp09d.gif",
        "https://files.catbox.moe/krjamq.gif",
        "https://files.catbox.moe/n2zpix.gif",
    ],
    "meme": [
        "https://files.catbox.moe/2tpt83.gif",
        "https://files.catbox.moe/2tpt83.gif",
        "https://files.catbox.moe/j4xmh5.png",
        "https://files.catbox.moe/jcgsur.jpg",
        "https://files.catbox.moe/481y7t.jpg",
        "https://files.catbox.moe/k1ugj2.jpg",
        "https://files.catbox.moe/szk0o4.jpg",
        "https://files.catbox.moe/l2j1w3.jpg",
        "https://files.catbox.moe/uqstlh.jpg",
        "https://files.catbox.moe/sazt4v.png",
        "https://files.catbox.moe/zxwkjo.jpg",
        "https://files.catbox.moe/gwifej.png",
    ],
    # "videos" : [
    #     "https://telegra.ph/file/f2235dde2263d69cb5e22.mp4",
    #     "https://telegra.ph/file/d414452895ef211ecb8d7.mp4"
    # ]
}
